# Generated by Django 3.2 on 2021-06-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, unique=True)),
                ('text', models.CharField(blank=True, max_length=150, null=True)),
                ('prix', models.FloatField()),
                ('_product_image', models.ImageField(blank=True, null=True, upload_to='product_img')),
            ],
        ),
    ]
