# Generated by Django 3.2 on 2021-07-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='1500', upload_to='product_img', width_field='1000'),
        ),
    ]
