# Generated by Django 3.1.4 on 2020-12-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_auto_20201230_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kid',
            old_name='parent_id',
            new_name='parentfr',
        ),
        migrations.AlterField(
            model_name='kid',
            name='kid_image',
            field=models.ImageField(blank=True, null=True, upload_to='lettre_img'),
        ),
    ]
