# Generated by Django 3.1.4 on 2021-03-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210108_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='custom_image',
            new_name='_custom_image',
        ),
    ]
