# Generated by Django 3.1.4 on 2020-12-27 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('parent_image', models.ImageField(upload_to='lettre_img')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('kid_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('kid_image', models.ImageField(upload_to='lettre_img')),
                ('email', models.EmailField(max_length=254)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.parent')),
            ],
        ),
    ]
