# Generated by Django 3.1.4 on 2020-12-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_image',
            field=models.ImageField(null=True, upload_to='lettre_img'),
        ),
    ]
