# Generated by Django 3.1.4 on 2020-12-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_auto_20201230_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_image',
            field=models.ImageField(blank=True, null=True, upload_to='lettre_img'),
        ),
    ]
