# Generated by Django 3.1.4 on 2020-12-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_auto_20201230_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='parentfr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent.parent'),
        ),
    ]
