# Generated by Django 3.1.4 on 2020-12-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0005_auto_20201230_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kid',
            old_name='parentfr',
            new_name='parent',
        ),
    ]
